### ISSUE TITLE
missing weight file

### ISSUE THREAD

**Issue by sahanHe** [yongwuSHU/Advsal#1]
Hi, 
Can you kindly provide the weight file for `resnext_101_32x4d`
Thank you,
Sahan

**Comment by yongwuML** [comment]
hi, thank  you for your interest in our work. you can check Install dependencies.

**Comment by sahanHe** [comment]
I followed the install `dependancies` yet I get this following error 
```Traceback (most recent call last):
  File "testing.py", line 27, in <module>
    main()
  File "testing.py", line 23, in main
    runner.infer()
  File "/home/jovyan/pr_curves/Advsal/test/evaluation/run.py", line 29, in infer
    net = Net().cuda()
  File "/home/jovyan/pr_curves/Advsal/train/model/sodgan.py", line 10, in __init__
    resnext = ResNeXt101()
  File "/home/jovyan/pr_curves/Advsal/train/model/resnext101.py", line 12, in __init__
    net.load_state_dict(torch.load(resnext101_32_path))
  File "/home/jovyan/conda-envs/ptorch/lib/python3.7/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/jovyan/conda-envs/ptorch/lib/python3.7/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/jovyan/conda-envs/ptorch/lib/python3.7/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: ''```
as it cannot find the weight file for the model

**Comment by sahanHe** [comment]
Thanks for you quick reply
